# Generated by Django 6.0.2 on 2026-03-16 14:01

import contents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_type', models.CharField(choices=[('image', 'Image')], default='image', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allow', 'Allow'), ('review', 'Review'), ('block', 'Block'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('original_file', models.FileField(upload_to=contents.models.content_upload_to)),
                ('original_storage_key', models.CharField(blank=True, max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=30)),
                ('top_cosine', models.FloatField(blank=True, null=True)),
                ('top_phash_dist', models.IntegerField(blank=True, null=True)),
                ('top_match', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('watermark', models.JSONField(blank=True, default=dict)),
                ('timing_ms', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
