# Generated by Django 6.0.4 on 2026-05-08 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0005_content_document_metadata_and_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["owner", "-created_at"], name="content_owner_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["owner", "source_sha256"], name="content_owner_sha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["-updated_at"], name="content_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["decision", "-created_at"], name="content_decision_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["status", "-created_at"], name="content_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voteparticipationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="vote_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voteparticipationlog",
            index=models.Index(
                fields=["content", "-created_at"], name="vote_content_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voteparticipationlog",
            index=models.Index(fields=["token_id"], name="vote_token_idx"),
        ),
    ]
