# Generated by Codex on 2026-03-17

from django.db import migrations


def add_missing_account_columns(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection
    quote_name = schema_editor.quote_name

    User = apps.get_model("accounts", "User")
    SocialAccount = apps.get_model("accounts", "SocialAccount")

    existing_tables = set(introspection.table_names())
    user_table = User._meta.db_table
    social_table = SocialAccount._meta.db_table
    q_user_table = quote_name(user_table)
    q_social_table = quote_name(social_table)

    if user_table in existing_tables:
        user_columns = {
            column.name for column in introspection.get_table_description(connection.cursor(), user_table)
        }
        with connection.cursor() as cursor:
            if "phone_verified_at" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN phone_verified_at timestamp with time zone NULL")
            if "nickname" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN nickname varchar(30) NULL")
                cursor.execute(f"UPDATE {q_user_table} SET nickname = username WHERE nickname IS NULL")
            if "display_name" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN display_name varchar(50) NULL")
                cursor.execute(f"UPDATE {q_user_table} SET display_name = COALESCE(username, '') WHERE display_name IS NULL")
            if "profile_image" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN profile_image varchar(200) NULL")
            if "auth_provider" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN auth_provider varchar(20) NULL")
                cursor.execute(f"UPDATE {q_user_table} SET auth_provider = 'local' WHERE auth_provider IS NULL")
            if "is_profile_completed" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN is_profile_completed boolean NULL")
                cursor.execute(f"UPDATE {q_user_table} SET is_profile_completed = false WHERE is_profile_completed IS NULL")
            if "terms_agreed_at" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN terms_agreed_at timestamp with time zone NULL")
            if "privacy_agreed_at" not in user_columns:
                cursor.execute(f"ALTER TABLE {q_user_table} ADD COLUMN privacy_agreed_at timestamp with time zone NULL")

    if social_table in existing_tables:
        social_columns = {
            column.name for column in introspection.get_table_description(connection.cursor(), social_table)
        }
        if "last_login_at" not in social_columns:
            with connection.cursor() as cursor:
                cursor.execute(f"ALTER TABLE {q_social_table} ADD COLUMN last_login_at timestamp with time zone NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_socialaccount_last_login_at"),
    ]

    operations = [
        migrations.RunPython(
            add_missing_account_columns,
            migrations.RunPython.noop,
        ),
    ]
