# Generated by Codex on 2026-03-17

from django.db import migrations


def add_missing_smsverification_columns(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection
    quote_name = schema_editor.quote_name

    SmsVerification = apps.get_model("accounts", "SmsVerification")
    sms_table = SmsVerification._meta.db_table

    existing_tables = set(introspection.table_names())
    if sms_table not in existing_tables:
        return

    sms_columns = {
        column.name for column in introspection.get_table_description(connection.cursor(), sms_table)
    }
    q_sms_table = quote_name(sms_table)

    with connection.cursor() as cursor:
        if "user_id" not in sms_columns:
            cursor.execute(f"ALTER TABLE {q_sms_table} ADD COLUMN user_id bigint NULL")
            cursor.execute(
                f"CREATE INDEX IF NOT EXISTS {quote_name('accounts_smsverification_user_id_idx')} "
                f"ON {q_sms_table} (user_id)"
            )
        if "purpose" not in sms_columns:
            cursor.execute(f"ALTER TABLE {q_sms_table} ADD COLUMN purpose varchar(20) NULL")
            cursor.execute(f"UPDATE {q_sms_table} SET purpose = 'signup' WHERE purpose IS NULL")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_backfill_missing_account_columns"),
    ]

    operations = [
        migrations.RunPython(
            add_missing_smsverification_columns,
            migrations.RunPython.noop,
        ),
    ]
