# Generated by Django 6.0.4 on 2026-05-08 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_aijob_progress"),
        ("contents", "0006_content_content_owner_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["owner", "-created_at"], name="aijob_owner_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["content", "job_type", "-created_at"],
                name="aijob_content_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["status", "-created_at"], name="aijob_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["job_type", "status", "-created_at"],
                name="aijob_type_status_created_idx",
            ),
        ),
    ]
