# Generated by Django 6.0.2 on 2026-03-30 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('verified', 'Verified'), ('candidate', 'Candidate')], max_length=20)),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('uploaded_file_size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_preview_url', models.URLField(blank=True, null=True)),
                ('detect', models.JSONField(blank=True, default=dict)),
                ('blockchain', models.JSONField(blank=True, default=dict)),
                ('candidate', models.JSONField(blank=True, default=dict)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
