# Generated by Django 6.0.4 on 2026-05-08 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0003_verificationhistorylog_uploaded_storage_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="verificationhistorylog",
            index=models.Index(
                fields=["user", "-created_at"], name="verifylog_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationhistorylog",
            index=models.Index(
                fields=["outcome", "-created_at"], name="verifylog_outcome_created_idx"
            ),
        ),
    ]
