# Generated by Codex on 2026-05-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contents", "0007_content_verified_status_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[("terms", "Terms"), ("privacy", "Privacy")],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["policy_type", "-published_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="RetentionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("delete_content", "Delete Content"),
                            ("anonymize_user", "Anonymize User"),
                            ("purge_upload", "Purge Upload"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="requested",
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(max_length=60)),
                ("target_id", models.CharField(max_length=120)),
                ("reason", models.TextField()),
                ("decision_note", models.TextField(blank=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retention_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("related_type", models.CharField(blank=True, max_length=60)),
                ("related_id", models.CharField(blank=True, max_length=120)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ModerationCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("needs_review", "Needs Review"),
                            ("hide", "Hide"),
                            ("restore", "Restore"),
                            ("reanalyze", "Reanalyze"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="resolved",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("previous_decision", models.CharField(blank=True, max_length=20)),
                ("next_status", models.CharField(blank=True, max_length=20)),
                ("next_decision", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_cases",
                        to="contents.content",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="ReportCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("copyright", "Copyright"),
                            ("impersonation", "Impersonation"),
                            ("abuse", "Abuse"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cases",
                        to="contents.content",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_update", "User Update"),
                            ("content_moderation", "Content Moderation"),
                            ("report_update", "Report Update"),
                            ("retention_update", "Retention Update"),
                            ("notification_create", "Notification Create"),
                            ("job_retry", "Job Retry"),
                            ("job_cancel", "Job Cancel"),
                            ("policy_publish", "Policy Publish"),
                        ],
                        max_length=40,
                    ),
                ),
                ("target_type", models.CharField(max_length=60)),
                ("target_id", models.CharField(max_length=120)),
                ("reason", models.TextField(blank=True)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, max_length=80)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="UserPolicyConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consented_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_consents",
                        to="operations.policyversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-consented_at"]},
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("policy_type", "version"), name="uniq_policy_type_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="userpolicyconsent",
            constraint=models.UniqueConstraint(
                fields=("user", "policy_version"), name="uniq_user_policy_consent"
            ),
        ),
        migrations.AddIndex(
            "retentionrequest",
            models.Index(
                fields=["status", "-created_at"], name="retention_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            "retentionrequest",
            models.Index(
                fields=["target_type", "target_id"], name="retention_target_idx"
            ),
        ),
        migrations.AddIndex(
            "notification",
            models.Index(
                fields=["user", "-created_at"], name="notice_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            "notification",
            models.Index(
                fields=["status", "-created_at"], name="notice_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            "moderationcase",
            models.Index(
                fields=["content", "-created_at"], name="modcase_content_created_idx"
            ),
        ),
        migrations.AddIndex(
            "moderationcase",
            models.Index(
                fields=["action", "-created_at"], name="modcase_action_created_idx"
            ),
        ),
        migrations.AddIndex(
            "reportcase",
            models.Index(
                fields=["status", "-created_at"], name="report_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            "reportcase",
            models.Index(
                fields=["content", "-created_at"], name="report_content_created_idx"
            ),
        ),
        migrations.AddIndex(
            "adminactionlog",
            models.Index(
                fields=["action", "-created_at"], name="oplog_action_created_idx"
            ),
        ),
        migrations.AddIndex(
            "adminactionlog",
            models.Index(fields=["target_type", "target_id"], name="oplog_target_idx"),
        ),
        migrations.AddIndex(
            "adminactionlog",
            models.Index(
                fields=["actor", "-created_at"], name="oplog_actor_created_idx"
            ),
        ),
    ]
